### PR TITLE
Try update to SDK 20.08

### PR DESCRIPTION
**Pull request by sjentsch**
Tried to update to 20.08 and removed Python 2.7 shared modules (hoping that it is a leftover and not really needed).

### CODE REVIEW

**Comment by hfiguiere** [comment]
> Tried to update to 20.08 and removed Python 2.7 shared modules (hoping that it is a leftover and not really needed).

given the manifest is trying to build node, I'm sure we can point the failure in that direction... if it's actually failing.

**Comment by sjentsch** [comment]
@hfiguiere You won. I had to put it back... ;-)

**Comment by jonathon-love** [comment]
i got building against 20.08 working a while back here:

https://github.com/jonathon-love/org.jamovi.jamovi/tree/2008-runtime

but it seg faults like a mofo, and i've no idea why, nor the skill to debug it. the fact that we build and distribute across so many systems, with so many different compiler/OS combos, without issue, leaves me slightly at a loss here.

**Comment by sjentsch** [comment]
Thanks, Jonathon.
I was wondering whether the segfaults may have to do with the shared modules being quite old / outdated? The commit that is linked there is from January 2020 (i.e., preceding the date of the SDK August 2020). I just tried to check out / upgrading to the most recent commit (`git submodule update --remote --merge shared-modules`) and will try to build and run it. If I am successful I will report back.

**Pull request closed without merging**
